apiVersion: v1
kind: Pod
metadata:
  name: sender
  labels:
    app: tcp-sender
spec:
  terminationGracePeriodSeconds: 0
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: hosting
                operator: In
                values:
                  - node
  containers:
    - name: sender
      image: flok3n/sender_tcp:1.0.1
      imagePullPolicy: Always
      command:
        [
          "python3",
          "/sender_tcp.py",
          "tcp-recv.default.svc.cluster.local",
          "8959",
        ]
---
apiVersion: v1
kind: Pod
metadata:
  name: receiver
  labels:
    app: tcp-recv
spec:
  terminationGracePeriodSeconds: 0
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: hosting
                operator: In
                values:
                  - redis
  containers:
    - name: receiver
      image: flok3n/receiver_tcp:1.0.0
      imagePullPolicy: Always
      command: ["python3", "/receiver_tcp.py", "8959"]
      ports:
        - containerPort: 8959
---
apiVersion: v1
kind: Service
metadata:
  name: tcp-recv
spec:
  selector:
    app: tcp-recv
  ports:
    - protocol: TCP
      port: 8959
      targetPort: 8959
