apiVersion: v1
kind: Pod
metadata:
  name: sender
  labels:
    app: udp-sender
spec:
  terminationGracePeriodSeconds: 0
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: hosting
                operator: In
                values:
                  - node
  containers:
    - name: sender
      image: flok3n/sender_udp:1.0.0
      imagePullPolicy: Always
      command:
        ["python3", "/sender.py", "udp-recv.default.svc.cluster.local", "8959"]
---
apiVersion: v1
kind: Pod
metadata:
  name: receiver
  labels:
    app: udp-recv
spec:
  terminationGracePeriodSeconds: 0
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: hosting
                operator: In
                values:
                  - redis
  containers:
    - name: receiver
      image: flok3n/receiver_udp:1.0.0
      imagePullPolicy: Always
      command: ["python3", "/receiver.py", "8959"]
      ports:
        - containerPort: 8959
---
apiVersion: v1
kind: Service
metadata:
  name: udp-recv
spec:
  selector:
    app: udp-recv
  ports:
    - protocol: UDP
      port: 8959
      targetPort: 8959
