apiVersion: v1
kind: ConfigMap
metadata:
  name: nodeapp-config
data:
  redis_url: redis://redis-service.default.svc.cluster.local:6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-depl
  labels:
    app: nodeapp-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp-redis
  template:
    metadata:
      labels:
        app: nodeapp-redis
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: hosting
                    operator: In
                    values:
                      - redis
      containers:
        - name: nodeapp-redis
          image: redis
          ports:
            - containerPort: 6379
          command:
            ["redis-server", "--save", "20", "1", "--loglevel", "warning"]
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: nodeapp-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-depl
  labels:
    app: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: hosting
                    operator: In
                    values:
                      - node
      containers:
        - name: nodeapp
          image: flok3n/sample-app:3.0.0
          ports:
            - containerPort: 3002
          env:
            - name: PORT
              value: "3002"
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: nodeapp-config
                  key: redis_url
---
apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  selector:
    app: node
  type: NodePort
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 3002
      nodePort: 30007
